title: Page
pages: true
files: true
fields:
  staticSiteGenerator:
    label: Generate a static version of the site
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea