title: Site
columns:
  sidebar: 
    width: 1/3
    sections:
      pages:
        type: pages
        templates:
          - about
          - articles
          - reading

  left:
    width: 2/3
    sections:
      config: sections/config